### ISSUE TITLE
Delete login not working

### ISSUE THREAD

**Issue by arichia** [saltedge/saltedge-android#39]
new DeleteLoginConnector(callback).deleteLogin(loginSecret, customerSecret);

Delete login is called with parameters in wrong order.

**Comment by ConstantinKV** [comment]
@arichia Thank you for your attention. 
We have updated SDK. Now you should call deleteLogin with next params sequence.
```java
SERequestManager.getInstance().deleteLogin(customerSecret, loginSecret,
                        new DeleteLoginResult() {...});
```
