### ISSUE TITLE
Remove org.jetbrains:annotations-java5 from gradle

### ISSUE THREAD

**Issue by sboo** [saltedge/saltedge-android#66]
Hi,

`implementation 'org.jetbrains:annotations-java5:16.0.3'` causes conflicts when implementing in other projects.

Right now I'm implementing it like this:
```
implementation ('com.saltedge.sdk:saltedge-library:3.2.0@aar') {
        transitive = true
        exclude group: 'org.jetbrains' , module:'annotations-java5'
}
```

However to the best of my knowledge it shouldn't be in your build.gradle anyway.

Cheers,
Ramon

**Comment by ConstantinKV** [comment]
@sboo Thank you for your contribution.

**Comment by ConstantinKV** [comment]
@sboo dependency removed. Please check new version 3.2.1. If all ok please close the issue.

**Comment by sboo** [comment]
It compiles successfully without anymore issues. Thanks for the quick response
